dist: xenial
language: csharp
solution: ItemsPlanning.Pn.sln
mono: none
dotnet: 2.2
services:
  - mysql
script:
  - dotnet restore eFormAPI/Plugins/ItemsPlanning.Pn/ItemsPlanning.Pn.sln
  - dotnet build eFormAPI/Plugins/ItemsPlanning.Pn/ItemsPlanning.Pn.sln
  - dotnet test -v n eFormAPI/Plugins/ItemsPlanning.Pn/ItemsPlanning.Pn.Test/ItemsPlanning.Pn.Test.csproj
  - cd ../..
  - git clone --depth=50 --branch=stable https://github.com/microting/eform-angular-frontend.git microting/eform-angular-frontend
  - cp -av microting/eform-angular-itemsplanning-plugin/eform-client/src/app/plugins/modules/items-planning-pn microting/eform-angular-frontend/eform-client/src/app/plugins/modules/items-planning-pn
  - cp -av microting/eform-angular-itemsplanning-plugin/eform-client/e2e/Tests/items-planning-settings microting/eform-angular-frontend/eform-client/e2e/Tests/items-planning-settings
  - cp -av microting/eform-angular-itemsplanning-plugin/eform-client/e2e/Tests/items-planning-general microting/eform-angular-frontend/eform-client/e2e/Tests/items-planning-general
  - cp -av microting/eform-angular-itemsplanning-plugin/eform-client/e2e/Page\ objects/items-planning microting/eform-angular-frontend/eform-client/e2e/Page\ objects/items-planning
  - cp -av microting/eform-angular-itemsplanning-plugin/eform-client/wdio-headless-plugin-step2.conf.js microting/eform-angular-frontend/eform-client/wdio-headless-plugin-step2.conf.js
  - cd microting/eform-angular-frontend
  - dotnet restore -v q eFormAPI/eFormAPI.sln > dotnet_log 2>&1 &
  - dotnet build eFormAPI/eFormAPI.sln > dotnet_log 2>&1 &
  - cd ../..
  - mkdir -p microting/eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins
  - cp -av microting/eform-angular-itemsplanning-plugin/eFormAPI/eFormAPI.Web/Plugins/ItemsPlanning microting/eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins/ItemsPlanning
  - cd microting/eform-angular-frontend
  - cd eform-client && npm install
  - /home/travis/build/microting/eform-angular-itemsplanning-plugin/testinginstallpn.sh
  - npm start &
  - sleep 40
  - dotnet run --project ../eFormAPI/eFormAPI.Web/eFormAPI.Web.csproj > dotnet_log 2>&1 &
  - sleep 40
  - npm run testheadless
  - sleep 40
  - npm run testheadlessplugin
